name: Deploy to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Actualizado a v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Actualizado a v3
        with:
          node-version: '20' # También puedes especificar Node 20 si tu proyecto es compatible

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: echo "No build step necessary" # Cambia o elimina este paso si tienes un comando de build

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a proyecto-seg
          git push heroku main
