name: Nuclei - Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v4

     
      - name: Install Node.js dependencies
        run: |
          npm install

     
      - name: Start server
        run: |
          npm start &
        env:
          NODE_ENV: production  

      
      - name: Wait for server to start
        run: |
          timeout 15s bash -c 'until echo > /dev/tcp/localhost/3000; do sleep 1; done'

 
      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:3000/
          sarif_output: nuclei-results.sarif  # Generar archivo SARIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
      - name: Check SARIF file
        id: check_sarif
        run: |
          if [ -f "nuclei-results.sarif" ]; then
            echo "sarif_exists=true" >> $GITHUB_ENV
          else
            echo "sarif_exists=false" >> $GITHUB_ENV
          fi

  
      - name: GitHub Workflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts Update
        uses: github/codeql-action/upload-sarif@v3
        if: env.sarif_exists == 'true'
        with:
          sarif_file: nuclei-results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


