name: Nuclei - Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Escaneo programado diario
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
      # Paso para clonar el repositorio
      - uses: actions/checkout@v4

      # Instalar dependencias de Node.js
      - name: Install Node.js dependencies
        run: |
          npm install

      # Iniciar el servidor en segundo plano
      - name: Start server
        run: |
          npm start &
        env:
          NODE_ENV: production  # Cambia esto según tus necesidades

      # Esperar a que el servidor esté activo
      - name: Wait for server to start
        run: |
          timeout 30s bash -c 'until echo > /dev/tcp/localhost/3000; do sleep 1; done'

      # Ejecución de Nuclei para escaneo de vulnerabilidades
      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:3000/
          sarif-output: nuclei-results.sarif  # Habilitar la salida SARIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Subir el archivo SARIF para depuración (opcional)
      - name: Upload SARIF file for debugging
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results.sarif
          path: nuclei-results.sarif

      # Subir el archivo SARIF al tablero de seguridad
      - name: GitHub Security Dashboard Alerts Update
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: nuclei-results.sarif  # Ruta correcta del archivo SARIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Subir el log como artefacto para revisión
      - name: GitHub Workflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log


