name: Nuclei - Vulnerability Scan

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Start server
        run: |
          npm start &
        env:
          NODE_ENV: production

      - name: Wait for server to start
        run: |
          timeout 30s bash -c 'until echo > /dev/tcp/localhost/3000; do sleep 1; done'

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:3000/
          sarif-output: nuclei-results.sarif
          args: -debug

      - name: Validate SARIF file
        run: |
          curl -sL https://sarifvalidator.azurewebsites.net/api/validate -F "file=@nuclei-results.sarif"

      - name: Upload SARIF file for debugging
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results.sarif
          path: nuclei-results.sarif

      - name: GitHub Security Dashboard Alerts Update
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: nuclei-results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Workflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log


