name: Docker Image Security Scan

on:
  push:
    branches:
      - main
      - develop

jobs:
  docker_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build -t yo .

