name: Docker Image Security Scan

on:
  push:
    branches:
      - main
      - develop

jobs:
  docker_scan:
    runs-on: ubuntu-latest  # Define el entorno en el que se ejecutará el job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Descarga el código de tu repositorio

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Configura Docker Buildx para construir la imagen

      - name: Build Docker image
        run: docker build -t yo
